# Generated by Django 2.1.5 on 2019-02-06 16:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField()),
                ('age', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('worth', models.CharField(max_length=250)),
                ('daily_unique_users', models.IntegerField()),
                ('daily_page_views', models.IntegerField()),
                ('daily_revenue', models.CharField(max_length=250)),
                ('alexa_rank', models.CharField(max_length=250)),
                ('website_info', models.TextField()),
                ('basic_info', models.TextField()),
                ('dns_info', models.TextField()),
                ('ip_info', models.TextField()),
                ('whois_info', models.TextField()),
                ('seo_info', models.TextField()),
                ('similar_websites', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
