# Generated by Django 2.1.5 on 2019-02-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190206_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='daily_page_views',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='website',
            name='daily_unique_users',
            field=models.CharField(max_length=250),
        ),
    ]
